### ISSUE TITLE
Retry with www if url has null path

### ISSUE THREAD

**Issue by nokout** [AusDTO/discoCrawl#1]
Should we try the root path of domains with www if we get a 400 httpCode 
Transferred from: https://github.com/AusDTO/discoveryLayer/issues/53

**Comment by nokout** [comment]
I have added the wontfix label because it does not appear that this is a "real" problem because probability would suggest that the www host will be referenced somewhere else across the other 20M government resources anyhow.

**Comment by monkeypants** [comment]
if wontfix then closed
